[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' https://cdn.jsdelivr.net https://www.gstatic.com; style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://fonts.googleapis.com; img-src 'self' https://firebasestorage.googleapis.com data:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.firebaseio.com https://firebasestorage.googleapis.com"